site_name: WilsonXM's Notebook
site_url: https://wilsonxm.github.io

theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Subjects:
    - ADS:
      - 基础部分: ADS/[未完待补]高级数据结构与算法分析.md
      - 动态规划: ADS/Dynamic Programming.md
